dist: trusty
language: go
sudo: true
env:
  - NODE_VERSION="0.12"
install: true
addons:
  chrome: stable
  apt:
    update: true
before_install:
  - sudo apt-get install -y jq
  - sudo apt install -y chromium-browser
  - nvm install $NODE_VERSION
  - npm install crx
script:
  - chmod +x ./util/release.sh
  - ./util/release.sh