dist: bionic
language: node_js
node_js:
  - 12
sudo: true
install: true
addons:
  apt:
    update: true
cache:
  directories:
    - $HOME/node_modules

install:
  - export TRAVIS_COMMIT_DESCRIPTION=`git log -n 1`

script:
  - git config --global user.email $GITHUB_EMAIL
  - git config --global user.name $GITHUB_USERNAME
  - git remote rm origin 
  - git remote add origin https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG.git 
  - git symbolic-ref HEAD refs/heads/master
  - npm install
  - if [[ "$TRAVIS_COMMIT_DESCRIPTION" != *"Release v"* ]];then npm run release --minor --ci; fi