dist: xenial
language: node_js
sudo: true
install: true
addons:
  apt:
    update: true
cache:
  directories:
    - $HOME/node_modules

install:
  - sudo apt-get install -y jq

script:
  - chmod +x ./util/release.sh
  - ./util/release.sh