language: javascript
sudo: true
dist: trusty
install: true
addons:
  chrome: stable
before_install:
  - wget https://dl.google.com/go/go1.12.2.linux-amd64.tar.gz
  - sudo tar -xf go1.12.2.linux-amd64.tar.gz
  - sudo mv go /usr/local
  - export GOROOT=/usr/local/go
addons:
  apt:
    update: true
script:
  - chmod +x ./util/release.sh
  - ./util/release.sh