dist: bionic
language: node_js
node_js:
  - 12
sudo: true
install: true
addons:
  apt:
    update: true
cache:
  directories:
    - $HOME/node_modules

install:
  - sudo apt-get install -y jq

script:
  - git remote rm origin 
  - git remote add origin https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG.git 
  - git symbolic-ref HEAD refs/heads/master
  - npm install
  - npm run release --minor --ci