dist: bionic
language: node_js
node_js:
  - 12
sudo: true
install: true
git:
  depth: false
addons:
  apt:
    update: true
cache:
  directories:
    - $HOME/node_modules

install:
  - sudo apt-get install -y jq

script:
  - chmod +x ./util/release.sh
  - ./util/release.sh