dist: trusty
language: javascript
sudo: true
install: true
addons:
  chrome: stable
  apt:
    update: true
before_install:
  - sudo apt-get install -y jq
  - sudo apt install -y chromium-browser
script:
  - chmod +x ./util/release.sh
  - ./util/release.sh